### ISSUE TITLE
Remove Discord link from toolbar

### ISSUE THREAD

**Issue by ghost** [arduino/forum-assets#301]
Discord is a social media platform that shouldn't interfere with the Arduino community. Due, to it's addition in the toolbar, people now may also flock over to discord ( especially those who have an interest in gaming ), and think the forum useless. Plus, discord is NOT A TECHNICAL FORUM like the Arduino forum. People will be asking questions in thee wrong place ( discord instead of the forum ).  I suggest let discord go it's own way and remove it from the toolbar so that people KNOW where to post questions.

Thanks.

**Comment by BallscrewBob** [comment]
As a social media platform it would be better moved to the lower bar along with the other social media sites.

It is presently too near the forum option and some users may mis-click on it by accident and think they were kicked out of the arduino site due to the exceptionally confusing way discord is laid out.
I would second the move to the lower area and its removal from the top toolbar.

**Comment by supernova-ws** [comment]
Does not relate to forum.

**Comment by BallscrewBob** [comment]
@supernova-ws could you direct to the correct section please.

**Comment by TLS-Rocketry** [comment]
Yes please direct this post to the correct section ( Move it please ).
