### ISSUE TITLE
Quoting code in code tags looses the language specifier

### ISSUE THREAD

**Issue by sterretjeToo** [arduino/forum-assets#360]
### Describe the problem

Quoting the below in a post loses the `cpp` [language identifier](https://www.markdownguide.org/extended-syntax/#syntax-highlighting)

````markdown
```cpp
some cpp code here
```
````

results in:

````markdown
[quote]
```
some cpp code here
```
[/quote]
````

See https://forum.arduino.cc/t/automatic-code-highlighting-do-you-want-it-or-not/868319/22 and [23](https://forum.arduino.cc/t/automatic-code-highlighting-do-you-want-it-or-not/868319/23)

### Suggested correction

Expected behaviour is that language specifier will not be affected when quoting code

#### Additional Reports

- https://forum.arduino.cc/t/my-code-is-now-posted-in-monochrome/1117879

### Issue checklist

- [X] I searched for previous reports in [the issue tracker](https://github.com/arduino/forum-assets/issues?q=)
- [X] My report contains all necessary details

**Comment by per1234** [comment]
A formal bug report has now been submitted for this upstream:

https://meta.discourse.org/t/language-identifier-is-missing-from-fenced-code-block-when-it-is-quoted/327895

This means that no further action is needed from Arduino, since the deficiency is in the Discourse forum framework (or perhaps in one of their dependencies), and the forum will be automatically updated to the version that has the fix once the Discourse developers make one.

Discourse is free open source software, so if any Arduino community members would like to move this forward they are welcome to submit a fix to the relevant codebase. There is information about contributing development work to the Discourse project here:

https://meta.discourse.org/t/contributing-to-discourse-development/3823
